### ISSUE TITLE
Make address click and copy

### ISSUE THREAD

**Issue by brklyn8900** [joticajulian/kondor#43]

**Comment by pgarciagon** [comment]
I would be nice to implement the address as in memamask: slightly increase of font-size, add a copy to clipboard icon and put the address  in the format "0x9BB...e888".

Instead of so:
![kondor_adress](https://user-images.githubusercontent.com/203416/206161145-ae2ee20d-26df-4902-b815-647cd73d0d23.png)

so:
![metamask_adress](https://user-images.githubusercontent.com/203416/206161179-cc1ddfbf-0e09-4d6b-9742-8d13f574b5a7.png)
